### ISSUE TITLE
Handling of `Serilog.Events.LogEvent` in `LokiBatchFormatter` is not thread-safe

### ISSUE THREAD

**Issue by k-wojcik** [serilog-contrib/serilog-sinks-grafana-loki#224]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

v8.2.0

### Which version of .NET are you using?

net6.0

### Describe the bug

Handling of `Serilog.Events.LogEvent` in `LokiBatchFormatter` is not thread-safe. 
Method `AddLevelAsPropertySafely` modifies `Serilog.Events.LogEvent.Properties` (`Dictionary<string, LogEventPropertyValue>`) and causes problems with simultaneous aceess to it from other threads (sinks).

https://github.com/serilog-contrib/serilog-sinks-grafana-loki/blob/master/src/Serilog.Sinks.Grafana.Loki/LokiBatchFormatter.cs#L157-L158

<img width="712" alt="image" src="https://github.com/serilog-contrib/serilog-sinks-grafana-loki/assets/832549/837bb742-8871-490b-811b-f4b74833c1bb">

https://github.com/serilog/serilog/issues/1154#issuecomment-387895863
_Serilog's LogEvent is not thread-safe for readers concurrent with writers; concurrent reads are fine, but only in the absence of writes_

### To Reproduce

Configure at least one sink with async processing alongside Serilog.Sinks.Grafana.Loki, for example I use sinks:
- Serilog.Sinks.Async + Serilog.Sinks.File, 
- Serilog.Sinks.Seq

### Expected behavior

The original value of `Serilog.Events.LogEvent.Properties` should never be modified in sink.

### Log/SelfLog output or exception with stacktrace

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Serilog.Formatting.Compact.CompactJsonFormatter.FormatEvent(LogEvent logEvent, TextWriter output, JsonValueFormatter valueFormatter)
   at Serilog.Sinks.Seq.ConstrainedBufferedFormatter.Format(LogEvent logEvent, TextWriter output, Boolean writePlaceholders)
```

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by ramonesz297** [comment]
Faced the same issue, but decided to write [own version](https://github.com/ramonesz297/yet-another-serilog-sinks-loki), as this implementation has problems with performance (especially memory allocations). 

One of optimization was to avoid any modifications of original `LogEvent`, that fixed the issue.

I do not think that my version can do all this package can, as my implementation target net6, net8 only, and (may be ) do not handle all cases, but for my purposes, where allocation is critical it is ok.

Anyway, maybe some ideas can be useful and applicable to this package as well.

**Comment by mishamyte** [comment]
Thanks for sharing, @ramonesz297.

Yeah, I agree about the perf-related things, they are noted.
I'm also not happy with some features, that brought complexity and perf downgrade, so thinking about their future in the next release. 

Hope your version will be useful for people, who struggle with some current behavior and characteristics

**Comment by mishamyte** [comment]
@oliver-unifii sorry to hear that and hope you will find the alternative solution, which will fit your requirements

**Comment by mishamyte** [comment]
Fixed in [v9.0.0](https://www.nuget.org/packages/Serilog.Sinks.Grafana.Loki/9.0.0) by design - `LokiBatchFormatter` is gone and the new pipeline never mutates `LogEvent` instances.

v9 is a ground-up rewrite - migration notes: [Upgrading from v8 to v9](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Upgrading-from-v8-to-v9). The new serialization path is also ~55× lighter on allocations and ~4.5× faster on the common workload ([Benchmarks](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Benchmarks)).
