### ISSUE TITLE
Memory leak inside LokiSink when invalid loki uri provided

### ISSUE THREAD

**Issue by forik** [serilog-contrib/serilog-sinks-grafana-loki#90]
### Which version of Serilog.Sinks.Grafana.Loki are you using?

7.1.0

### Which version of .NET are you using?

net6

### Describe the bug

Memory leak when invalid loki url provided

### To Reproduce

Set loki uri to "" (string.Empty)

### Expected behavior

No memory leak

### Log/SelfLog output or exception with stacktrace

2022-03-11T09:10:23.0135906Z Exception while emitting periodic batch from Serilog.Sinks.Grafana.Loki.LokiSink: System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.PostAsync(String requestUri, HttpContent content)
   at Serilog.Sinks.Grafana.Loki.HttpClients.LokiHttpClient.PostAsync(String requestUri, Stream contentStream) in /_/src/Serilog.Sinks.Grafana.Loki/HttpClients/LokiHttpClient.cs:line 39
   at Serilog.Sinks.Grafana.Loki.LokiSink.OnTick() in /_/src/Serilog.Sinks.Grafana.Loki/LokiSink.cs:line 127

### Additional context

The code inside LokiSink.cs doesn't clear _waitingBatch on exception while sending data using httpClient
https://github.com/serilog-contrib/serilog-sinks-grafana-loki/blob/dbf6095d581ceb5bf499bb98247eec79c0e8c5c0/src/Serilog.Sinks.Grafana.Loki/LokiSink.cs#L156

I think _waiting batch needs also to be cleared as on unsuccessful http response 

### I have read the documentation

- [X] I have read [Common Problems](https://github.com/serilog-contrib/serilog-sinks-grafana-loki/wiki/Common-problems) section in project wiki

**Comment by mishamyte** [comment]
Hi @forik,

Thank you for this founding. By design we don't clear the batch in case of exception to have a possibility for resubmit (e.g. network failures, Loki unavailability etc).

But I will investigate this case

**Comment by forik** [comment]
Hi @mishamyte, thanks for response. Will close this one then.
